/*
 * Scala bean class for entity table AUTHOR 
 * Created on 18 avr. 2013 ( Date ISO 2013-04-18 - Time 11:51:30 )
 * Generated by Telosys Tools Generator ( version 2.0.3 )
 */

package org.demo.bean

import scala.beans.BeanProperty


/**
 * Entity bean for table "AUTHOR"
 * 
 * @author Telosys Tools Generator
 *
 */
class AuthorExplicit extends Serializable
{
    private val serialVersionUID = 1L

    private var id          :Int   =_   // Primary Key

    private var firstName   : String   =_      
    private var lastName    : String   =_      

//----------------------------------------------------------------------
// GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
//----------------------------------------------------------------------
    /**
     * Set the "id" field value
     * This field is mapped on the database column "ID" ( type "INTEGER", NotNull : true ) 
     * @param id
     */
	def setId(id:Int ) = {
        this.id = id
    }
    /**
     * Get the "id" field value
     * This field is mapped on the database column "ID" ( type "INTEGER", NotNull : true ) 
     * @return the field value
     */
    def getId():Int = this.id// ou def getId = this.id
    

//----------------------------------------------------------------------
// GETTER(S) & SETTER(S) FOR DATA FIELDS
//----------------------------------------------------------------------
    //--- DATABASE MAPPING : FIRST_NAME ( VARCHAR ) 
    /**
     * Set the "firstName" field value
     * This field is mapped on the database column "FIRST_NAME" ( type "VARCHAR", NotNull : false ) 
     * @param firstName
     */
	def setFirstName(firstName: String ) = {
        this.firstName = firstName
    }
    /**
     * Get the "firstName" field value
     * This field is mapped on the database column "FIRST_NAME" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    def getFirstName(): String  = this.firstName// ou def getFirstName = this.firstName

    //--- DATABASE MAPPING : LAST_NAME ( VARCHAR ) 
    /**
     * Set the "lastName" field value
     * This field is mapped on the database column "LAST_NAME" ( type "VARCHAR", NotNull : false ) 
     * @param lastName
     */
	def setLastName(lastName: String ) = {
        this.lastName = lastName
    }
    /**
     * Get the "lastName" field value
     * This field is mapped on the database column "LAST_NAME" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    def getLastName(): String  = this.lastName// ou def getLastName = this.lastName


}
